### ISSUE TITLE
[Feedback:CreatedOnDate] not supported in Comments template

### ISSUE THREAD

**Issue by TopCat6** [DNNCommunity/DNN.Feedback#19]
The 'available tokens' shows this should work: [Feedback:CreatedOnDate] in the Comments template. However, FeedbackInfo.vb supports only "createdondateutc" or "datecreated" as tokens. Perhaps "createdondate" should be added to the list to be consistent with the token help list.

**Comment by valadas** [comment]
@TopCat6 ends up there was a property DateCreated but the token help said CreatedOnDate. I have updated the token help for next release, so you should use [Feedback:DateCreated] instead of [Feedback:CreatedOnDate]. I did not want to change the actual property on people already using it, so I just changed the help text.
